FROM golang:1.21 AS builder
WORKDIR /app
COPY voting.proto decision_coordinator.go .
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest \
    && go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest \
    && protoc --go_out=. --go-grpc_out=. voting.proto \
    && go build -o coordinator .

FROM scratch
COPY --from=builder /app/coordinator /coordinator
ENTRYPOINT ["/coordinator"]