# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: twopc.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'twopc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btwopc.proto\x12\x05twopc\"%\n\x0bVoteRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\"y\n\tVoteReply\x12+\n\x08\x64\x65\x63ision\x18\x01 \x01(\x0e\x32\x19.twopc.VoteReply.Decision\x12\x12\n\nreplica_id\x18\x02 \x01(\t\"+\n\x08\x44\x65\x63ision\x12\x0f\n\x0bVOTE_COMMIT\x10\x00\x12\x0e\n\nVOTE_ABORT\x10\x01\x32\x35\n\x05TwoPC\x12,\n\x04Vote\x12\x12.twopc.VoteRequest\x1a\x10.twopc.VoteReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'twopc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOTEREQUEST']._serialized_start=22
  _globals['_VOTEREQUEST']._serialized_end=59
  _globals['_VOTEREPLY']._serialized_start=61
  _globals['_VOTEREPLY']._serialized_end=182
  _globals['_VOTEREPLY_DECISION']._serialized_start=139
  _globals['_VOTEREPLY_DECISION']._serialized_end=182
  _globals['_TWOPC']._serialized_start=184
  _globals['_TWOPC']._serialized_end=237
# @@protoc_insertion_point(module_scope)
